services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    depends_on:
      - rest
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
    ports:
      - 8080:8080
      - 10000:10000
      - 10001:10001
  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    ports:
      - 8182:8181
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://iceberg_data/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  antalya:
    #image: clickhouse:24.12.3.47
    image: altinity/clickhouse-server:24.12.2.20101.altinityantalya
    container_name: antalya
    hostname: antalya
    ports:
      - 9000:9000
    volumes:
      - ./config.d/antalya:/etc/clickhouse-server/config.d
      - ./users.d:/etc/clickhouse-server/users.d
      - ./logs/antalya:/var/log/clickhouse-server
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
  keeper:
    image: altinity/clickhouse-keeper:24.12.2.20101.altinityantalya
    container_name: keeper
    hostname: keeper
    ports:
      - 2181:2181
    volumes:
      # Note special location of Keeper config overrides. 
      - ./config.d/keeper:/etc/clickhouse-keeper/keeper_config.d
      - ./logs/keeper:/var/log/clickhouse-keeper
  swarm-1:
    #image: clickhouse:24.12.3.47
    image: altinity/clickhouse-server:24.12.2.20101.altinityantalya
    container_name: swarm-1
    hostname: swarm-1
    volumes:
      - ./config.d/swarm:/etc/clickhouse-server/config.d
      - ./users.d:/etc/clickhouse-server/users.d
      - ./logs/swarm-1:/var/log/clickhouse-server
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
  swarm-2:
    #image: clickhouse:24.12.3.47
    image: altinity/clickhouse-server:24.12.2.20101.altinityantalya
    container_name: swarm-2
    hostname: swarm-2
    volumes:
      - ./config.d/swarm:/etc/clickhouse-server/config.d
      - ./users.d:/etc/clickhouse-server/users.d
      - ./logs/swarm-2:/var/log/clickhouse-server
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DOMAIN=minio
    networks:
      default:
        aliases:
          - warehouse.minio
    ports:
        - 9001:9001
        - 9002:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse --ignore-existing;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
